# Generated by Django 2.2.28 on 2022-04-15 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=15)),
                ('username', models.CharField(blank=True, max_length=15)),
                ('password', models.CharField(blank=True, max_length=15)),
                ('recipient', models.CharField(blank=True, max_length=15)),
                ('messagetype', models.CharField(blank=True, max_length=15)),
                ('originator', models.CharField(blank=True, max_length=15)),
                ('messagedata', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MessageManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid number', regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
