# Generated by Django 2.2.28 on 2022-04-15 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageManager',
        ),
    ]
